name: via

on:
  schedule:
    # Run every 3 hours (at minute 0)
    - cron: "0 */3 * * *"
  workflow_dispatch:

# Ensure only one workflow run executes at a time across the repo.
# New runs will wait (be queued) until the current one finishes.
concurrency:
  group: "via-workflow"
  cancel-in-progress: false

# Allow the cleanup step to cancel jobs (needs 'actions: write').
permissions:
  contents: read
  actions: write

env:
  MAX_WORKERS: "20"

jobs:
  export-and-run:
    runs-on: ubuntu-22.04

    # exactly 20 parallel workers per workflow run
    strategy:
      matrix:
        worker: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download
        shell: bash
        run: |
          curl -fsSL -o via.zip "${{ secrets.VIA }}"
          if [ ! -f "via.zip" ]; then
            echo "Download failed: via.zip not found."
            exit 1
          fi

      - name: Unzip
        shell: bash
        run: |
          unzip -q via.zip
          rm -f via.zip

      - name: Make runner executable
        shell: bash
        run: |
          chmod +x ./via.sh

      - name: Run worker
        shell: bash
        env:
          WORKER_ID: ${{ matrix.worker }}
          MAX_WORKERS: ${{ env.MAX_WORKERS }}
        run: |
          echo "Starting worker $WORKER_ID of $MAX_WORKERS"
          ./via.sh "$WORKER_ID"
